//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 17.0.32113.165
// 
namespace CMS.EdamamApiClient {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoodDataObject", Namespace="http://tempuri.org/")]
    public partial class FoodDataObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string FoodNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FoodName {
            get {
                return this.FoodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodNameField, value) != true)) {
                    this.FoodNameField = value;
                    this.RaisePropertyChanged("FoodName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EdamamApiClient.EdamamFoodServiceSoap")]
    public interface EdamamFoodServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFood", ReplyAction="*")]
        System.Threading.Tasks.Task<CMS.EdamamApiClient.getFoodResponse> getFoodAsync(CMS.EdamamApiClient.getFoodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFoodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFood", Namespace="http://tempuri.org/", Order=0)]
        public CMS.EdamamApiClient.getFoodRequestBody Body;
        
        public getFoodRequest() {
        }
        
        public getFoodRequest(CMS.EdamamApiClient.getFoodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFoodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string foodName;
        
        public getFoodRequestBody() {
        }
        
        public getFoodRequestBody(string foodName) {
            this.foodName = foodName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFoodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFoodResponse", Namespace="http://tempuri.org/", Order=0)]
        public CMS.EdamamApiClient.getFoodResponseBody Body;
        
        public getFoodResponse() {
        }
        
        public getFoodResponse(CMS.EdamamApiClient.getFoodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFoodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CMS.EdamamApiClient.FoodDataObject getFoodResult;
        
        public getFoodResponseBody() {
        }
        
        public getFoodResponseBody(CMS.EdamamApiClient.FoodDataObject getFoodResult) {
            this.getFoodResult = getFoodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EdamamFoodServiceSoapChannel : CMS.EdamamApiClient.EdamamFoodServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EdamamFoodServiceSoapClient : System.ServiceModel.ClientBase<CMS.EdamamApiClient.EdamamFoodServiceSoap>, CMS.EdamamApiClient.EdamamFoodServiceSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EdamamFoodServiceSoapClient() : 
                base(EdamamFoodServiceSoapClient.GetDefaultBinding(), EdamamFoodServiceSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.EdamamFoodServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EdamamFoodServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(EdamamFoodServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), EdamamFoodServiceSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EdamamFoodServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EdamamFoodServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EdamamFoodServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EdamamFoodServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EdamamFoodServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMS.EdamamApiClient.getFoodResponse> CMS.EdamamApiClient.EdamamFoodServiceSoap.getFoodAsync(CMS.EdamamApiClient.getFoodRequest request) {
            return base.Channel.getFoodAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMS.EdamamApiClient.getFoodResponse> getFoodAsync(string foodName) {
            CMS.EdamamApiClient.getFoodRequest inValue = new CMS.EdamamApiClient.getFoodRequest();
            inValue.Body = new CMS.EdamamApiClient.getFoodRequestBody();
            inValue.Body.foodName = foodName;
            return ((CMS.EdamamApiClient.EdamamFoodServiceSoap)(this)).getFoodAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.EdamamFoodServiceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.EdamamFoodServiceSoap)) {
                return new System.ServiceModel.EndpointAddress("https://localhost:44339/EdamamFoodService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return EdamamFoodServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.EdamamFoodServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return EdamamFoodServiceSoapClient.GetEndpointAddress(EndpointConfiguration.EdamamFoodServiceSoap);
        }
        
        public enum EndpointConfiguration {
            
            EdamamFoodServiceSoap,
        }
    }
}
